version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: dc-openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./data/openvpn-data/conf:/etc/openvpn

